### ISSUE TITLE
Demo not working, Mixed Content

### ISSUE THREAD

**Issue by ontwikkelfabriek** [Piterden/vue-crossword#24]
Demo is not working anymore due to Mixed content (connecting to http url).

**Comment by Piterden** [comment]
Yes, I know. Unfortunately I can't make certificate for IP address. And also, I am rewriting this app to vanilla-js and electron. The reason is because separated front with fetching data from API as HTTP request is very slow. When app will make direct queries to DB, avoiding slow network, it promises to be very fast!

**Comment by Piterden** [comment]
https://user-images.githubusercontent.com/5930429/105531534-83ef2780-5cfa-11eb-8ec4-c9d298b82826.mp4

**Comment by Piterden** [comment]
https://user-images.githubusercontent.com/5930429/105531564-8fdae980-5cfa-11eb-8edb-0e92658cab02.mp4

**Comment by Piterden** [comment]
https://user-images.githubusercontent.com/5930429/105531578-9701f780-5cfa-11eb-8372-dbfb2b2f11d0.mp4

**Comment by Piterden** [comment]
Here is some demo as video

**Comment by Piterden** [comment]
Fixed
